services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "./app"
    container_name: app
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass